id: A412A9797
title: Advice for Urgyen Tsomo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:13:46.653682
  last_modified_at: 2022-02-28 23:13:46.653686
