id: A412A9797
title: Prayer to Karmapa Khakyab Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:13:46.657958
  last_modified_at: 2022-02-28 23:13:46.657963
