id: A412A9797
title: Prayer to Buddha Amitābha
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:13:46.656592
  last_modified_at: 2022-02-28 23:13:46.656596
