id: A412A9797
title: A Prayer to Khandro Yeshé Tsogyal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:13:46.651814
  last_modified_at: 2022-02-28 23:13:46.651821
